a,b=5,10.5
c=a+b
#print(c)
print(type(a))
print(type(b))
print(type(c))
#print("the type of variable a is {}".format(a1))
#print("the type of variable b is {}".format(b1))
print("the value of a is {}".format(a))
print("the value of b is {}".format(b))
print("the sum of a and b is : {} ".format(c))
print("-----------------------------------------")
string = "PytHon"
print(string)
print(string.capitalize())
print(string.upper())
print(string.lower())
print(string.isalnum())
print(string.isalpha())
print(string.isdecimal())
print(string.replace("n","N"))
print(string.find("a"))
print(string.partition("yt"))
print(string.__len__())
print(string.swapcase())
print(" ")
print('___________________________________________')


list_name=["Apple","Banana","Cucumber","Drumstick"]
print(list_name)
list_name.reverse()
print(list_name)
#print(list_name[2])
#list_name.append("Elephant")
#print(list_name)
#list_name.pop(2)
#print(list_name)
#list_name.sort()
#print(list_name)
#print(list_name.__getitem__(3))
#print(list_name.__contains__("Apple"))
list1=[1,2,3,4,5]
print(list1)
list1.reverse()
print(list1)
